import '../models/course_model.dart';
import '../models/topic_model.dart';
import '../models/task_model.dart';
import '../models/exam_model.dart';

/// Smart scheduling algorithm.
///
/// Strategy:
/// 1. Collect all pending topics (not completed).
/// 2. Score each topic using a weighted formula considering:
///    - Priority of parent course
///    - Topic difficulty
///    - Days until nearest exam in the same course
///    - Days until course deadline
///    - Remaining study hours
/// 3. Sort topics by score (descending).
/// 4. Allocate time slots day-by-day:
///    - Respect daily hour limit
///    - Start from preferredStartHour
///    - Insert 15-min breaks between sessions
///    - Don't schedule past deadlines
///    - Don't schedule on days where limit is already reached
/// 5. Return generated StudyTask list.
class SmartScheduler {
  final List<Course> courses;
  final List<Topic> topics;
  final List<Exam> exams;
  final List<StudyTask> existingTasks; // tasks already scheduled
  final double dailyHoursLimit;
  final int preferredStartHour; // 0–23
  final int breakMinutesBetweenSessions;
  final int maxDaysAhead;

  SmartScheduler({
    required this.courses,
    required this.topics,
    required this.exams,
    required this.existingTasks,
    this.dailyHoursLimit = 3.0,
    this.preferredStartHour = 9,
    this.breakMinutesBetweenSessions = 15,
    this.maxDaysAhead = 60,
  });

  List<StudyTask> generate() {
    final generated = <StudyTask>[];
    if (dailyHoursLimit <= 0) return generated;

    // Build a map of courseId → nearest exam date
    final examDateByCourse = <String, DateTime>{};
    for (final exam in exams) {
      if (!exam.isPast) {
        final existing = examDateByCourse[exam.courseId];
        if (existing == null || exam.examDate.isBefore(existing)) {
          examDateByCourse[exam.courseId] = exam.examDate;
        }
      }
    }

    // Build course map for quick lookup
    final courseMap = {for (final c in courses) c.id: c};

    // Filter to schedulable topics (not completed, course exists & active)
    final schedulable = topics.where((t) {
      if (t.isCompleted) return false;
      final course = courseMap[t.courseId];
      if (course == null || course.isArchived) return false;
      // Don't schedule if course deadline has passed
      if (course.deadline.isBefore(DateTime.now())) return false;
      return true;
    }).toList();

    // Score and sort topics
    final scored = schedulable.map((t) {
      final course = courseMap[t.courseId]!;
      final score = _score(t, course, examDateByCourse[t.courseId]);
      return _ScoredTopic(topic: t, course: course, score: score);
    }).toList()
      ..sort((a, b) => b.score.compareTo(a.score));

    // Track how many hours are allocated per calendar date
    final hoursAllocated = <String, double>{};

    // Seed with existing non-completed auto-generated tasks
    for (final task in existingTasks) {
      if (!task.completed && task.isAutoGenerated) {
        final key = _dayKey(task.scheduledDate);
        hoursAllocated[key] = (hoursAllocated[key] ?? 0) + task.duration;
      }
    }

    // Allocate new sessions
    final today = DateTime.now();

    for (final item in scored) {
      double remaining = item.topic.estimatedHours;
      if (item.topic.isInProgress) {
        // Rough estimate: assume 50% done if in progress
        remaining *= 0.5;
      }

      final deadline = item.course.deadline;
      final examDate = examDateByCourse[item.course.id];
      final effectiveDeadline = examDate != null && examDate.isBefore(deadline)
          ? examDate
          : deadline;

      int dayOffset = 0;

      while (remaining > 0.01 && dayOffset <= maxDaysAhead) {
        final date = today.add(Duration(days: dayOffset));

        // Don't schedule past effective deadline
        if (date.isAfter(effectiveDeadline)) break;

        final key = _dayKey(date);
        final usedHours = hoursAllocated[key] ?? 0;
        final available = dailyHoursLimit - usedHours;

        if (available > 0.1) {
          // Allocate minimum of remaining work or available slot
          // Use session chunks of at most 2 hours
          final chunk = [remaining, available, 2.0].reduce((a, b) => a < b ? a : b);
          final roundedChunk = (chunk * 4).round() / 4.0; // round to 15 min

          if (roundedChunk >= 0.25) {
            // Calculate start time
            final scheduledMinutes = (usedHours * 60).toInt();
            final startHour = preferredStartHour + scheduledMinutes ~/ 60;
            final startMinute = scheduledMinutes % 60;

            final scheduledDate = DateTime(
              date.year,
              date.month,
              date.day,
              startHour.clamp(0, 23),
              startMinute,
            );

            generated.add(StudyTask(
              id: '${item.topic.id}_${scheduledDate.millisecondsSinceEpoch}',
              courseId: item.course.id,
              topicId: item.topic.id,
              title:
                  '${item.course.name} — ${item.topic.name}',
              scheduledDate: scheduledDate,
              duration: roundedChunk,
              priority: _taskPriority(item.course.priority),
              isAutoGenerated: true,
            ));

            hoursAllocated[key] = usedHours + roundedChunk +
                (breakMinutesBetweenSessions / 60.0);
            remaining -= roundedChunk;
          }
        }

        dayOffset++;
      }
    }

    // Sort by date ascending
    generated.sort((a, b) => a.scheduledDate.compareTo(b.scheduledDate));
    return generated;
  }

  /// Weighted score: higher = schedule sooner.
  double _score(Topic topic, Course course, DateTime? examDate) {
    double score = 0;

    // Priority weight
    score += course.priorityValue * 20;

    // Difficulty weight (harder topics first)
    score += topic.difficulty * 10;

    // Urgency: days until exam (fewer = more urgent)
    if (examDate != null) {
      final daysToExam = examDate.difference(DateTime.now()).inDays;
      if (daysToExam > 0) {
        score += (60.0 / daysToExam).clamp(0, 60);
      } else {
        score += 60; // past exam — still schedule for completeness
      }
    }

    // Urgency: days until course deadline
    final daysToDead = course.deadline.difference(DateTime.now()).inDays;
    if (daysToDead > 0) {
      score += (30.0 / daysToDead).clamp(0, 30);
    } else {
      score += 30;
    }

    // Penalise very long topics so shorter ones can interleave
    score -= topic.estimatedHours * 0.5;

    // Bonus for in-progress topics
    if (topic.isInProgress) score += 15;

    return score;
  }

  TaskPriority _taskPriority(String coursePriority) {
    switch (coursePriority.toLowerCase()) {
      case 'urgent':
        return TaskPriority.urgent;
      case 'high':
        return TaskPriority.high;
      case 'low':
        return TaskPriority.low;
      default:
        return TaskPriority.medium;
    }
  }

  static String _dayKey(DateTime d) =>
      '${d.year}-${d.month}-${d.day}';
}

class _ScoredTopic {
  final Topic topic;
  final Course course;
  final double score;

  _ScoredTopic({
    required this.topic,
    required this.course,
    required this.score,
  });
}
