import 'dart:convert';

enum TaskStatus { todo, inProgress, completed }
enum TaskPriority { low, medium, high, urgent }

class StudyTask {
  final String id;
  final String userId;
  final String courseId;
  final String topicId;
  final String title;
  final String description;
  final DateTime scheduledDate;
  final double duration; // hours
  final TaskStatus status;
  final TaskPriority priority;
  final DateTime? deadline;
  final bool isAutoGenerated; // from scheduler
  final String notes;
  final DateTime createdAt;

  StudyTask({
    required this.id,
    this.userId = '',
    required this.courseId,
    this.topicId = '',
    this.title = '',
    this.description = '',
    DateTime? scheduledDate,
    DateTime? date,
    this.duration = 1.0,
    TaskStatus? status,
    bool? completed,
    this.priority = TaskPriority.medium,
    this.deadline,
    this.isAutoGenerated = false,
    this.notes = '',
    DateTime? createdAt,
  })  : scheduledDate = scheduledDate ?? date ?? DateTime.now(),
        status = status ?? (completed == true ? TaskStatus.completed : TaskStatus.todo),
        createdAt = createdAt ?? DateTime.now();

  DateTime get date => scheduledDate;
  bool get completed => status == TaskStatus.completed;
  bool get isOverdue =>
      deadline != null &&
      deadline!.isBefore(DateTime.now()) &&
      status != TaskStatus.completed;

  String get priorityLabel => priority.name.substring(0, 1).toUpperCase() +
      priority.name.substring(1);

  StudyTask copyWith({
    String? id,
    String? userId,
    String? courseId,
    String? topicId,
    String? title,
    String? description,
    DateTime? scheduledDate,
    double? duration,
    TaskStatus? status,
    TaskPriority? priority,
    DateTime? deadline,
    bool? isAutoGenerated,
    String? notes,
    DateTime? createdAt,
  }) {
    return StudyTask(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      courseId: courseId ?? this.courseId,
      topicId: topicId ?? this.topicId,
      title: title ?? this.title,
      description: description ?? this.description,
      scheduledDate: scheduledDate ?? this.scheduledDate,
      duration: duration ?? this.duration,
      status: status ?? this.status,
      priority: priority ?? this.priority,
      deadline: deadline ?? this.deadline,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      notes: notes ?? this.notes,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'user_id': userId,
      'course_id': courseId,
      'topic_id': topicId,
      'title': title,
      'description': description,
      'scheduled_date': scheduledDate.millisecondsSinceEpoch,
      'duration': duration,
      'status': status.index,
      'priority': priority.index,
      'deadline': deadline?.millisecondsSinceEpoch,
      'is_auto_generated': isAutoGenerated ? 1 : 0,
      'notes': notes,
      'created_at': createdAt.millisecondsSinceEpoch,
    };
  }

  factory StudyTask.fromMap(Map<String, dynamic> map) {
    return StudyTask(
      id: map['id'] as String,
      userId: (map['user_id'] ?? '') as String,
      courseId: (map['course_id'] ?? '') as String,
      topicId: (map['topic_id'] ?? '') as String,
      title: (map['title'] ?? '') as String,
      description: (map['description'] ?? '') as String,
      scheduledDate: map['scheduled_date'] != null
          ? DateTime.fromMillisecondsSinceEpoch(map['scheduled_date'] as int)
          : (map['date'] != null
              ? DateTime.fromMillisecondsSinceEpoch(map['date'] as int)
              : DateTime.now()),
      duration: ((map['duration'] ?? 1.0) as num).toDouble(),
      status: _parseStatus(map),
      priority: TaskPriority.values[(map['priority'] ?? 1) as int],
      deadline: map['deadline'] != null
          ? DateTime.fromMillisecondsSinceEpoch(map['deadline'] as int)
          : null,
      isAutoGenerated:
          map['is_auto_generated'] == 1 || map['is_auto_generated'] == true,
      notes: (map['notes'] ?? '') as String,
      createdAt: map['created_at'] != null
          ? DateTime.fromMillisecondsSinceEpoch(map['created_at'] as int)
          : DateTime.now(),
    );
  }

  static TaskStatus _parseStatus(Map<String, dynamic> map) {
    // Support old 'completed' boolean field from legacy data
    if (map.containsKey('status')) {
      final v = map['status'];
      if (v is int) return TaskStatus.values[v];
    }
    if (map['completed'] == 1 || map['completed'] == true) {
      return TaskStatus.completed;
    }
    return TaskStatus.todo;
  }

  String toJson() => jsonEncode(toMap());
  factory StudyTask.fromJson(String source) =>
      StudyTask.fromMap(jsonDecode(source) as Map<String, dynamic>);
}
